#!/usr/bin/env bash
set -e

teardown() {
  local tear_down_script="$project/teardown.sh"

  if [ -f "$tear_down_script" ]; then
    bash "$tear_down_script" | tee -a "$build_log"
  fi
}

run() {
  set +e
  output=$(bash "$run_script")
  status=$?
  set -e
  echo "$output" | tee -a "$build_log"
}

run_project() {
  local run_script="$project/run.sh"
  local output

  if [ -f "$run_script" ]; then
    if [ ! -f "$project/.lock" ]; then
      touch "$project/.lock"
      run
      teardown
      rm "$project/.lock"
    else
      echo "Project already running."
    fi
  else
    echo "Cannot find run.sh"
    status=1
  fi
}

next_run_number() {
  run_number=$(($(ls "$project/builds" | sort -nr | head -n 1) + 1))
}

project="$1"
if [ -d "$project" ]; then
  mkdir -p "$project/builds"
  next_run_number
  mkdir -p "$project/builds/$run_number"
  build_log="$project/builds/$run_number/log"
  touch "$build_log"

  run_project
else
  echo "Directory '$project' does not exist."
  exit 1
fi

if [ "$status" -eq 0 ]; then
  echo "SUCCESS" | tee -a "$build_log"
  exit 0
else
  echo "FAILURE" | tee -a "$build_log"
  exit 1
fi
